### ISSUE TITLE
Bilder-Einstellungs Tab wird im Administrationsbereich nicht geladen

### ISSUE THREAD

**Issue by oli-f** [veenmeyer/Einsatzkomponente#61]
Da der Fieldset-Namen "config" im Administrationsbereich anscheinend mehrfach verwendet wird, kommt es zu einem Fehlverhalten (Bilder Einstellungs-Tab wird nicht geladen)
Behoben werden kann das Problem durch ändern des Fieldset-Names in der config.xml zu z.B. "img_config" (Nebenwirkungen noch nicht ausgiebig getestet)

**Comment by veenmeyer** [comment]
Vielen Dank für den Hinweis, wurde bereits in der Beta-Version behoben.
