### ISSUE TITLE
/administrator/components/com_einsatzkomponente/assets/bootstrap/css/bootstrap.min.css veraltet bzw. Grid-Modul fehlt

### ISSUE THREAD

**Issue by oli-f** [veenmeyer/Einsatzkomponente#62]
Im aktuellen Einsatzfahrzeug-Template wird das Grid-Modul von Bootstrap verwendet, um den Text neben dem Bild anzuzeigen - dies funktioniert jedoch nicht.
Der Grund dafür ist, dass in der aktuellen bootstrap.min.css das Grid-Modul fehlt, behoben werden kann das durch das verwenden der aktuellen bootstrap.min.css

**Comment by veenmeyer** [comment]
In der aktuellen Beta habe ich die neue Bootstrap-Version hinzugefügt.
